spring.application.name=axis
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/axis_db
spring.datasource.username=axis_user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=axis
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.create-schemas=true
spring.flyway.schemas=axis
spring.flyway.default-schema=axis